[build]
builder = "nixpacks"

[deploy]
startCommand = "flask db upgrade && gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
